-- MySQL Script generated by MySQL Workbench
-- Thu May 18 19:39:54 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema admgr
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `slots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `slots` (
  `date` DATE NOT NULL,
  `position` INT(11) NOT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `created` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `modified` DATETIME(3) NULL DEFAULT NULL,
  `booked_date` DATETIME NULL DEFAULT NULL,
  `booked_by` VARCHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`date`, `position`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transactions` (
  `txnid` VARCHAR(36) NULL DEFAULT NULL,
  `created` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  `date` DATE NOT NULL,
  `position` INT(11) NOT NULL,
  PRIMARY KEY (`date`, `position`),
  CONSTRAINT `fk_slots_transaction`
    FOREIGN KEY (`date` , `position`)
    REFERENCES `slots` (`date` , `position`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
