instance_id: admgr

host: localhost
port: 10001

# logger configuration
logger:
  level: debug
  full_timestamp: true
  output_file_path: "./admgr.log"

# redis connection information
redis:
  host: localhost
  port: 6379
  username: ""
  password: ""

# db connection information
db:
  host: localhost
  port: 3306
  name: "admgr"
  username: "root"
  password: "password"

# external service connection information
accounting:
  host: http://localhost
  port: 10002