instance_id: admgr

host: localhost
port: 10001

# logger configuration
logger:
  level: debug
  full_timestamp: true
  output_file_path: "/var/log/admgr/admgr.log"

# redis connection information
redis:
  host: localhost
  port: 6379
  username: ""
  password: ""

# db connection information
db:
  host: localhost
  port: 3306
  name: "adsvc"
  username: "adsvc"
  password: "abc123"
